language: node_js

before_install:
  - npm i -g lerna
  - npm i -g gatsby-cli

install:
  - yarn

script:
  - yarn build
  - yarn test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: packages/website/
  on:
    branch: master

addons:
  browserstack:
    username: 'adriengrsmto'
    access_key:
      secure: 'D75arx7W8WEGPIDHbWNrvttP3kbT5u8w+QXXYAP/DNH3012BoThNLmIB9U8YAxOccrC0ZISQq8d73/aX70A0S97IJpFQv9wwIS540JwawKSJc23OeKNsImobeNdK0k2al8JvKonIaPJzexKTNHwV7OYxzFxIotGrIQsImjC38Pw='
